topic: /keyboard_teleop/input
publish_rate: 20.0
velocity_step: 0.2

input_code:
  damping: 1
  ready_pose: 2
  velocity: 3
  mimic: 4

selector_navigation:
  initial_code: 200
  options:
    - {code: 200, label: MimicSquat}
    - {code: 201, label: MimicDance1}
    - {code: 202, label: MimicDance2}
